### ISSUE TITLE
README lacks instructions on how to download dependencies

### ISSUE THREAD

**Issue by walro** [bearburger/twingly-search-api-javascript#7]
Suppose it's `npm install`

**Comment by walro** [comment]
When I install I get:

`npm WARN twingly-search-api@1.0.1 No repository field.`

**Comment by bearburger** [comment]
Well required dependencies will be installed with library when user executed `npm install twingly-search-api`.

About `dev` dependencies. You get warning because repository field was actually missed in `package.json` (fixed). Besides of that warning you see no other messages because you already have all dependencies installed. To test `dev` deps installation you can remove `node_modules` directory and run `npm install`.
